### ISSUE TITLE
How can I make the crowdsale without any closing date

### ISSUE THREAD

**Issue by Speedevs** [vittominacori/ico-maker#2]
Is there any way I can remove the closing date for the crowdsale and make it mintable ,because I have seen the mintable code but want to remove the closing date ?

**Comment by vittominacori** [comment]
Remove the `TimedCrowdsale` [here](https://github.com/vittominacori/ico-maker/blob/master/contracts/crowdsale/BaseCrowdsale.sol#L14) and the related behaviours like opening and closing time.

Then extend `MintedCrowdsale`.

**Comment by Speedevs** [comment]
Ok ,but found out that the @import in the top the open Zeppelin files are missing in the repo you imported

**Comment by vittominacori** [comment]
Yes you must add 

```
import "@openzeppelin/contracts/crowdsale/emission/MintedCrowdsale.sol";
```
as in [MintedBaseCrowdsale](https://github.com/vittominacori/ico-maker/blob/master/contracts/crowdsale/MintedBaseCrowdsale.sol)

**Comment by Speedevs** [comment]
Ok thanks
